from django.urls import path
from .views import *

urlpatterns = [
    path('homeview', homeview,name='homeview'),
    path('jobdetail/<int:id>/', jobdetail,name='jobdetail'),
    path('employeeregister', employee_register,name='employeeregister'),
    path('employeelogin', employee_login,name='employeelogin'),
    path('employeelogout', employee_logout,name='employeelogout'),
    path('employeeprofile', employee_profile,name='employeeprofile'),
    path('applyjob/<int:id>/', applyjob, name='applyjob'),
    path('companyregister', company_register,name='companyregister'),
    path('companylogin', company_login,name='companylogin'),
    path('companylogout', company_logout,name='companylogout'),
    path('company_index', companyview,name='company_index'),
    path('editemployeeprofile/<int:id>/', edit_employee_profile, name='edit_employee_profile'),
    path('companypost', post,name='companypost'),
    path('companyprofile/<int:id>/', company_profile,name='companyprofile'),
    path('editcompanyprofile/<int:id>/', edit_company_profile, name='editcompanyprofile'),
    path('companypostview/<int:id>/', company_post_view, name='companypostview'),
    path('editpost/<int:id>/', edit_post, name='editpost'),
    path('deletepost/<int:id>/', deletepost, name='deletepost'),
    path('viewapply/<int:id>/', view_apply, name='viewapply'),
    path('careerquiz', career_quiz, name='careerquiz'),
    path('calculatematch', calculate_match, name='calculate_match'),
    path('employeelist', employeelist, name='employeelist'),
    path('companylist', companylist, name='companylist'),
    path('profile', profile, name='profile'),
    path('application', application, name='application'),
    path('chart', chart, name='chart'),
    path('logout', logoutview, name='logout'),
    path('adminview/', AdminView.as_view(), name='adminview'),
    path('login/',loginview,name='login'),
    path('register/',register_view,name='register'),
    path('employee_detail/<int:id>/', employee_detail, name='employee_detail'),
    path('delete_employee/<int:id>/', delete_employee, name='delete_employee'),
    path('company_detail/<int:id>/', company_detail, name='company_detail'),
    path('delete_company/<int:id>/', delete_company, name='delete_company'),
    path('company_list_view', company_list_view, name='company_list_view'),
    path('applied_job', applied_job, name='applied_job'),
    path('hiring_analytics', hiring_analytics, name='hiring_analytics'),
    path('result_history', result_history, name='result_history'),
    path('savejob/<int:id>/', savejob, name='savejob'),
    path('check_apply/<int:id>/', check_apply, name='check_apply'),
    path('employeeprofileview/<int:id>/',employee_profile_view,name='employeeprofileview'),
    path('company_candidates', company_candidates, name='company_candidates'),
    path('intro', intro, name='intro'),
    path('employeeprofileview/<int:id>/',employee_profile_view,name='employeeprofileview'),
    path('company_candidates', company_candidates, name='company_candidates'),
    path('company-job-detail/<int:id>/',company_job_detail,name='company_job_detail'),
    path('job_applicants/<int:id>/',job_applicants,name='job_applicants'),
    path('application/status/<int:id>/',update_application_status,name='update_application_status'),
    path('viewcompanydetail/<int:id>/', view_company_detail,name='viewcompanydetail'),
    path('savedjobs', saved_jobs,name='savedjobs'),
    path('showpost/<int:id>/', show_post,name='showpost'),
  


]