# Generated by Django 6.0.3 on 2026-07-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_company_facebook_company_linkedin_company_tagline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_save',
            field=models.BooleanField(default=False),
        ),
    ]
