# Generated by Django 6.0.7 on 2026-07-22 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_job_is_save_savejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email_provider',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook'), ('custom', 'Custom')], default='gmail', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.CreateModel(
            name='ApplicationEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.jobapplication')),
            ],
        ),
    ]
