# Generated by Django 6.0.7 on 2026-07-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_company_email_password_company_email_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='email_password',
            new_name='email_app_password',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
