# Generated by Django 6.0.7 on 2026-07-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_email_password_company_email_app_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='email_sent',
            new_name='accepted_email_sent',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='rejected_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='shortlisted_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
