# Generated by Django 6.0.7 on 2026-07-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_email_sent_jobapplication_accepted_email_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='accepted_email_sent',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='rejected_email_sent',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='shortlisted_email_sent',
        ),
        migrations.AddField(
            model_name='applicationemail',
            name='status',
            field=models.CharField(default='Pending', max_length=30),
            preserve_default=False,
        ),
    ]
